//
//  FoodLogApp.swift
//  FoodLog
//
//  Created by Mateus Mansuelli on 07/10/24.
//

import SwiftUI
import SwiftData

@main
struct FoodLogApp: App {
    var sharedModelContainer: ModelContainer = {
        let schema = Schema([
            Food.self,
        ])
        let modelConfiguration = ModelConfiguration(schema: schema, isStoredInMemoryOnly: false)

        do {
            let container = try ModelContainer(for: schema, configurations: [modelConfiguration])
            let fetchDescriptor = FetchDescriptor<Food>()
            
            if try container.mainContext.fetch(fetchDescriptor).count == 0 {
                container.mainContext.insert(Food(name: "Pizza", emoji: "🍕"))
                container.mainContext.insert(Food(name: "Burger", emoji: "🍔"))
                container.mainContext.insert(Food(name: "Sushi", emoji: "🍣"))
                container.mainContext.insert(Food(name: "Pasta", emoji: "🍝"))
                container.mainContext.insert(Food(name: "Taco", emoji: "🌮"))
                container.mainContext.insert(Food(name: "Burrito", emoji: "🌯"))
                container.mainContext.insert(Food(name: "Ice Cream", emoji: "🍦"))
                container.mainContext.insert(Food(name: "Shaved Ice", emoji: "🍧"))
                container.mainContext.insert(Food(name: "Cupcake", emoji: "🧁"))
                container.mainContext.insert(Food(name: "Apple", emoji: "🍎"))
                container.mainContext.insert(Food(name: "Banana", emoji: "🍌"))
                container.mainContext.insert(Food(name: "Strawberry", emoji: "🍓"))
                container.mainContext.insert(Food(name: "Cherries", emoji: "🍒"))
                container.mainContext.insert(Food(name: "Peach", emoji: "🍑"))
                container.mainContext.insert(Food(name: "Mango", emoji: "🥭"))
                container.mainContext.insert(Food(name: "Grapes", emoji: "🍇"))
                container.mainContext.insert(Food(name: "Watermelon", emoji: "🍉"))
                container.mainContext.insert(Food(name: "Lemon", emoji: "🍋"))
                container.mainContext.insert(Food(name: "Pineapple", emoji: "🍍"))
                container.mainContext.insert(Food(name: "Coconut", emoji: "🥥"))
                container.mainContext.insert(Food(name: "Kiwi", emoji: "🥝"))
                container.mainContext.insert(Food(name: "Avocado", emoji: "🥑"))
                container.mainContext.insert(Food(name: "Tomato", emoji: "🍅"))
                container.mainContext.insert(Food(name: "Carrot", emoji: "🥕"))
                container.mainContext.insert(Food(name: "Corn", emoji: "🌽"))
                container.mainContext.insert(Food(name: "Mushroom", emoji: "🍄"))
                container.mainContext.insert(Food(name: "Broccoli", emoji: "🥦"))
                container.mainContext.insert(Food(name: "Cheese", emoji: "🧀"))
                container.mainContext.insert(Food(name: "Bagel", emoji: "🥯"))
                container.mainContext.insert(Food(name: "Bacon", emoji: "🥓"))
                container.mainContext.insert(Food(name: "Hot Dog", emoji: "🌭"))
                container.mainContext.insert(Food(name: "Popcorn", emoji: "🍿"))
                container.mainContext.insert(Food(name: "Salad", emoji: "🥗"))
                container.mainContext.insert(Food(name: "Sandwich", emoji: "🥪"))
                container.mainContext.insert(Food(name: "Pretzel", emoji: "🥨"))
                container.mainContext.insert(Food(name: "French Fries", emoji: "🍟"))
                container.mainContext.insert(Food(name: "Onigiri", emoji: "🍙"))
                container.mainContext.insert(Food(name: "Ramen", emoji: "🍜"))
                container.mainContext.insert(Food(name: "Dango", emoji: "🍡"))
                container.mainContext.insert(Food(name: "Rice", emoji: "🍚"))
                container.mainContext.insert(Food(name: "Curry", emoji: "🍛"))
                container.mainContext.insert(Food(name: "Steak", emoji: "🥩"))
                container.mainContext.insert(Food(name: "Meat", emoji: "🍖"))
                container.mainContext.insert(Food(name: "Oyster", emoji: "🦪"))
                container.mainContext.insert(Food(name: "Clam", emoji: "🍥"))
                container.mainContext.insert(Food(name: "Lobster", emoji: "🦞"))
                container.mainContext.insert(Food(name: "Crab", emoji: "🦀"))
                container.mainContext.insert(Food(name: "Shrimp", emoji: "🍤"))
                container.mainContext.insert(Food(name: "Octopus", emoji: "🐙"))
                container.mainContext.insert(Food(name: "Fish", emoji: "🐟"))
                container.mainContext.insert(Food(name: "Bento Box", emoji: "🍱"))
                container.mainContext.insert(Food(name: "Cupcake", emoji: "🧁"))
                container.mainContext.insert(Food(name: "Pie", emoji: "🥧"))
                container.mainContext.insert(Food(name: "Birthday Cake", emoji: "🎂"))
                container.mainContext.insert(Food(name: "Chocolate Bar", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Cookie", emoji: "🍪"))
                container.mainContext.insert(Food(name: "Donut", emoji: "🍩"))
                container.mainContext.insert(Food(name: "Croissant", emoji: "🥐"))
                container.mainContext.insert(Food(name: "Pancakes", emoji: "🥞"))
                container.mainContext.insert(Food(name: "Honey Pot", emoji: "🍯"))
                container.mainContext.insert(Food(name: "Milk", emoji: "🥛"))
                container.mainContext.insert(Food(name: "Tea", emoji: "🍵"))
                container.mainContext.insert(Food(name: "Coffee", emoji: "☕"))
                container.mainContext.insert(Food(name: "Bubble Tea", emoji: "🧋"))
                container.mainContext.insert(Food(name: "Beer", emoji: "🍺"))
                container.mainContext.insert(Food(name: "Wine", emoji: "🍷"))
                container.mainContext.insert(Food(name: "Champagne", emoji: "🍾"))
                container.mainContext.insert(Food(name: "Cocktail", emoji: "🍸"))
                container.mainContext.insert(Food(name: "Tropical Drink", emoji: "🍹"))
                container.mainContext.insert(Food(name: "Sake", emoji: "🍶"))
                container.mainContext.insert(Food(name: "Green Tea", emoji: "🍵"))
                container.mainContext.insert(Food(name: "Rice Cracker", emoji: "🍘"))
                container.mainContext.insert(Food(name: "Fortune Cookie", emoji: "🥠"))
                container.mainContext.insert(Food(name: "Moon Cake", emoji: "🥮"))
                container.mainContext.insert(Food(name: "Hot Pepper", emoji: "🌶️"))
                container.mainContext.insert(Food(name: "Salt", emoji: "🧂"))
                container.mainContext.insert(Food(name: "Peanuts", emoji: "🥜"))
                container.mainContext.insert(Food(name: "Chestnut", emoji: "🌰"))
                container.mainContext.insert(Food(name: "Bread", emoji: "🍞"))
                container.mainContext.insert(Food(name: "Butter", emoji: "🧈"))
                container.mainContext.insert(Food(name: "Egg", emoji: "🥚"))
                container.mainContext.insert(Food(name: "Spaghetti", emoji: "🍝"))
                container.mainContext.insert(Food(name: "Waffle", emoji: "🧇"))
                container.mainContext.insert(Food(name: "Canned Food", emoji: "🥫"))
                container.mainContext.insert(Food(name: "Potato", emoji: "🥔"))
                container.mainContext.insert(Food(name: "Cucumber", emoji: "🥒"))
                container.mainContext.insert(Food(name: "Leafy Green", emoji: "🥬"))
                container.mainContext.insert(Food(name: "Bell Pepper", emoji: "🫑"))
                container.mainContext.insert(Food(name: "Olive", emoji: "🫒"))
                container.mainContext.insert(Food(name: "Garlic", emoji: "🧄"))
                container.mainContext.insert(Food(name: "Onion", emoji: "🧅"))
                container.mainContext.insert(Food(name: "Tomato", emoji: "🍅"))
                container.mainContext.insert(Food(name: "Sweet Potato", emoji: "🍠"))
                container.mainContext.insert(Food(name: "Chili Pepper", emoji: "🌶️"))
                container.mainContext.insert(Food(name: "Pickle", emoji: "🥒"))
                container.mainContext.insert(Food(name: "Baguette", emoji: "🥖"))
                container.mainContext.insert(Food(name: "Tortilla", emoji: "🌮"))
                container.mainContext.insert(Food(name: "Falafel", emoji: "🧆"))
                container.mainContext.insert(Food(name: "Empanada", emoji: "🥟"))
                container.mainContext.insert(Food(name: "Mango", emoji: "🥭"))
                container.mainContext.insert(Food(name: "Pomegranate", emoji: "🧃"))
                container.mainContext.insert(Food(name: "Tomato Soup", emoji: "🥫"))
                container.mainContext.insert(Food(name: "Blueberries", emoji: "🫐"))
                container.mainContext.insert(Food(name: "Kiwi", emoji: "🥝"))
                container.mainContext.insert(Food(name: "Coconut", emoji: "🥥"))
                container.mainContext.insert(Food(name: "Cantaloupe", emoji: "🍈"))
                container.mainContext.insert(Food(name: "Green Apple", emoji: "🍏"))
                container.mainContext.insert(Food(name: "Pear", emoji: "🍐"))
                container.mainContext.insert(Food(name: "Lemon", emoji: "🍋"))
                container.mainContext.insert(Food(name: "Melon", emoji: "🍈"))
                container.mainContext.insert(Food(name: "Grapefruit", emoji: "🍊"))
                container.mainContext.insert(Food(name: "Dragon Fruit", emoji: "🫐"))
                container.mainContext.insert(Food(name: "Tangerine", emoji: "🍊"))
                container.mainContext.insert(Food(name: "Eggplant", emoji: "🍆"))
                container.mainContext.insert(Food(name: "Beetroot", emoji: "🪴"))
                container.mainContext.insert(Food(name: "Radish", emoji: "🥗"))
                container.mainContext.insert(Food(name: "Zucchini", emoji: "🥒"))
                container.mainContext.insert(Food(name: "Sweetcorn", emoji: "🌽"))
                container.mainContext.insert(Food(name: "Pancake", emoji: "🥞"))
                container.mainContext.insert(Food(name: "Fish Cake", emoji: "🍥"))
                container.mainContext.insert(Food(name: "Rice Ball", emoji: "🍙"))
                container.mainContext.insert(Food(name: "Fried Shrimp", emoji: "🍤"))
                container.mainContext.insert(Food(name: "Sundae", emoji: "🍨"))
                container.mainContext.insert(Food(name: "Cake Slice", emoji: "🍰"))
                container.mainContext.insert(Food(name: "Lollipop", emoji: "🍭"))
                container.mainContext.insert(Food(name: "Candy", emoji: "🍬"))
                container.mainContext.insert(Food(name: "Rice Cracker", emoji: "🍘"))
                container.mainContext.insert(Food(name: "Turkey", emoji: "🦃"))
                container.mainContext.insert(Food(name: "Cherries", emoji: "🍒"))
                container.mainContext.insert(Food(name: "Boba", emoji: "🧋"))
                container.mainContext.insert(Food(name: "Frozen Yogurt", emoji: "🍦"))
                container.mainContext.insert(Food(name: "Soup", emoji: "🍲"))
                container.mainContext.insert(Food(name: "Hot Sauce", emoji: "🌶️"))
                container.mainContext.insert(Food(name: "Cappuccino", emoji: "☕"))
                container.mainContext.insert(Food(name: "Iced Coffee", emoji: "🥤"))
                container.mainContext.insert(Food(name: "Milkshake", emoji: "🥤"))
                container.mainContext.insert(Food(name: "Roasted Chicken", emoji: "🍗"))
                container.mainContext.insert(Food(name: "Bacon and Eggs", emoji: "🍳"))
                container.mainContext.insert(Food(name: "Boiled Egg", emoji: "🥚"))
                container.mainContext.insert(Food(name: "Scrambled Eggs", emoji: "🍳"))
                container.mainContext.insert(Food(name: "Green Salad", emoji: "🥗"))
                container.mainContext.insert(Food(name: "Caesar Salad", emoji: "🥗"))
                container.mainContext.insert(Food(name: "Fried Fish", emoji: "🐟"))
                container.mainContext.insert(Food(name: "BBQ Skewer", emoji: "🍢"))
                container.mainContext.insert(Food(name: "Spaghetti", emoji: "🍝"))
                container.mainContext.insert(Food(name: "Nachos", emoji: "🧀"))
                container.mainContext.insert(Food(name: "Meatball", emoji: "🍖"))
                container.mainContext.insert(Food(name: "Beef", emoji: "🥩"))
                container.mainContext.insert(Food(name: "Shish Kebab", emoji: "🍢"))
                container.mainContext.insert(Food(name: "Smoked Salmon", emoji: "🐟"))
                container.mainContext.insert(Food(name: "Chocolate Chip Cookie", emoji: "🍪"))
                container.mainContext.insert(Food(name: "Fruit Tart", emoji: "🍮"))
                container.mainContext.insert(Food(name: "Mousse", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Yogurt", emoji: "🥛"))
                container.mainContext.insert(Food(name: "Chili", emoji: "🌶️"))
                container.mainContext.insert(Food(name: "Pot Roast", emoji: "🍖"))
                container.mainContext.insert(Food(name: "Hot Cereal", emoji: "🥣"))
                container.mainContext.insert(Food(name: "Pita Bread", emoji: "🥙"))
                container.mainContext.insert(Food(name: "Stuffed Grape Leaves", emoji: "🍃"))
                container.mainContext.insert(Food(name: "Dumplings", emoji: "🥟"))
                container.mainContext.insert(Food(name: "Spring Roll", emoji: "🥟"))
                container.mainContext.insert(Food(name: "Baguette Bread", emoji: "🥖"))
                container.mainContext.insert(Food(name: "Salami", emoji: "🥓"))
                container.mainContext.insert(Food(name: "Gyoza", emoji: "🥟"))
                container.mainContext.insert(Food(name: "Tortilla Chips", emoji: "🌽"))
                container.mainContext.insert(Food(name: "Cheese Fondue", emoji: "🧀"))
                container.mainContext.insert(Food(name: "Fruit Salad", emoji: "🍇"))
                container.mainContext.insert(Food(name: "Roasted Veggies", emoji: "🥦"))
                container.mainContext.insert(Food(name: "Zoodles", emoji: "🥒"))
                container.mainContext.insert(Food(name: "Minestrone Soup", emoji: "🥣"))
                container.mainContext.insert(Food(name: "Gumbo", emoji: "🍛"))
                container.mainContext.insert(Food(name: "Pho", emoji: "🍲"))
                container.mainContext.insert(Food(name: "Chow Mein", emoji: "🍜"))
                container.mainContext.insert(Food(name: "Dim Sum", emoji: "🍤"))
                container.mainContext.insert(Food(name: "Clam Chowder", emoji: "🥣"))
                container.mainContext.insert(Food(name: "Fried Rice", emoji: "🍚"))
                container.mainContext.insert(Food(name: "Peking Duck", emoji: "🦆"))
                container.mainContext.insert(Food(name: "Bratwurst", emoji: "🌭"))
                container.mainContext.insert(Food(name: "Nacho Cheese", emoji: "🧀"))
                container.mainContext.insert(Food(name: "Custard", emoji: "🍮"))
                container.mainContext.insert(Food(name: "Gelato", emoji: "🍧"))
                container.mainContext.insert(Food(name: "Muffin", emoji: "🧁"))
                container.mainContext.insert(Food(name: "Popsicle", emoji: "🍡"))
                container.mainContext.insert(Food(name: "Egg Roll", emoji: "🥡"))
                container.mainContext.insert(Food(name: "Baklava", emoji: "🥧"))
                container.mainContext.insert(Food(name: "Churros", emoji: "🥖"))
                container.mainContext.insert(Food(name: "Chili Dog", emoji: "🌭"))
                container.mainContext.insert(Food(name: "Empanadas", emoji: "🥟"))
                container.mainContext.insert(Food(name: "Arepa", emoji: "🥙"))
                container.mainContext.insert(Food(name: "Fajitas", emoji: "🌮"))
                container.mainContext.insert(Food(name: "Tater Tots", emoji: "🥔"))
                container.mainContext.insert(Food(name: "Beef Stew", emoji: "🍲"))
                container.mainContext.insert(Food(name: "Seaweed Salad", emoji: "🥗"))
                container.mainContext.insert(Food(name: "Kimchi", emoji: "🥬"))
                container.mainContext.insert(Food(name: "Tempura", emoji: "🍤"))
                container.mainContext.insert(Food(name: "Omelette", emoji: "🍳"))
                container.mainContext.insert(Food(name: "Scrambled Eggs", emoji: "🍳"))
                container.mainContext.insert(Food(name: "Tiramisu", emoji: "🍰"))
                container.mainContext.insert(Food(name: "Fondant Cake", emoji: "🎂"))
                container.mainContext.insert(Food(name: "Eclairs", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Marshmallow", emoji: "🍬"))
                container.mainContext.insert(Food(name: "Fudge", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Truffle", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Peanut Butter", emoji: "🥜"))
                container.mainContext.insert(Food(name: "Hazelnut Spread", emoji: "🍫"))
                container.mainContext.insert(Food(name: "Raisin Bread", emoji: "🍞"))
                container.mainContext.insert(Food(name: "Cheesecake", emoji: "🍰"))
                container.mainContext.insert(Food(name: "Banana Split", emoji: "🍌"))
                container.mainContext.insert(Food(name: "Fruit Punch", emoji: "🥤"))

                
            }
            return container
        } catch {
            fatalError("Could not create ModelContainer: \(error)")
        }
    }()

    var body: some Scene {
        WindowGroup {
            MainView()
                .modelContainer(sharedModelContainer)
        }
    }
}
